name: fepi_local
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  
  connectivity_plus: ^6.1.1
  file_picker: ^8.1.5
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_pdfview: ^1.3.4
  flutter_signature_pad: ^3.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  mysql1: ^0.20.0
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  shared_preferences: ^2.3.3
  syncfusion_flutter_pdf: ^24.1.46
  table_calendar: ^3.1.3
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  go_router: ^14.6.2
  sqflite: ^2.0.0
  path: ^1.8.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.14.2


flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/ReciboMateriales.pdf
    - lib/assets/conafe_local.db
  fonts:
    - family: LexendDeca
      fonts:
        - asset: lib/assets/fonts/LexendDeca-Black.ttf
        - asset: lib/assets/fonts/LexendDeca-Bold.ttf
        - asset: lib/assets/fonts/LexendDeca-ExtraBold.ttf
        - asset: lib/assets/fonts/LexendDeca-Medium.ttf
    - family: Staatliches
      fonts:
        - asset: lib/assets/fonts/Staatliches-Regular.ttf


flutter_native_splash:
  color: "#FFFFFF" 
  image: lib/assets/logo.png 
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: lib/assets/icono1.png
  
